### ISSUE TITLE
Make it more generic

### ISSUE THREAD

**Issue by akorosov** [nansencenter/sea_ice_drift#1]
Currently the packages is very specific to Sentinel-1, Nansat, HV. However it has high potential for applications in other areas (bands, sensors, EM-range, etc). It is important to make it much more generic to be more widely usable.

**Comment by stefanmuckenhuber** [comment]
Thanks for the comment! I agree!
The current setting is tuned for Sentinel-1, but new test/tuning data from other sensors could give us the best possible setting for the respective images.
NB: The band can be changed to HH by adding band='HH' as argument.
