### ISSUE TITLE
'bool' object has no attribute 'children'

### ISSUE THREAD

**Issue by lucearth** [nansencenter/sea_ice_drift#13]
I am trying to open some .zip files dowloaded from the sentinel hub(with Nansat or get_n function). Normally I have no problem to do that,however for some images, it fails : 

/home/luc/miniconda/envs/test-environment/lib/python2.7/site-packages/nansat/mappers/mapper_sentinel1_l1.pyc in get_LUT_VRTs(self, XML, vectorListName, LUT_list)
    450             LUTs[LUT] = []
    451         xLengths = []
--> 452         for vec in vecList.children:
    453             xVec = list(map(int, vec['pixel'].split()))
    454             xLengths.append(len(xVec))

AttributeError: 'bool' object has no attribute 'children'

Any ideas about what is happening on some files ?  It is a bit problematic when I try to perform loop on a directory with a lot of image pairs,

Thanks a lot,

Luc

**Comment by akorosov** [comment]
It seems to be relevant for nansat package but I can reply here.

Which version of nansat do you have? Try to install the latest version. It is available only on PYPI so you can use pip from the conda environment with GDAL and other Nasnsat requirements installed:
`pip install nansat`

**Comment by hamoun1981** [comment]
I have the same problem.
I am able to run the algorithm and have results for following pairs of SAR images (which I downloaded them from the sentinel hub last year):
f1 = 'S1B_EW_GRDM_1SDH_20171224T092150_20171224T092250_008859_00FC9B_4A84.SAFE'
f2 = 'S1B_EW_GRDM_1SDH_20171227T094618_20171227T094718_008903_00FDFA_E50C.SAFE'

recently I downloaded 6 pairs of SAR images from the sentinel hub but for all of them I faced with this error (and still I do not have a problem for above-mentioned pair of SAR images):
AttributeError: 'bool' object has no attribute 'children'

I installed the sea_ice_drift package in my laptop as follow (I tried to install from recommended way, but it does not work for me):
- conda create --name py3drift python=3
- source activate py3drift
- conda install -c conda-forge nansat
- conda install gdal=2.2
- conda install opencv nose
- pip install https://github.com/nansencenter/sea_ice_drift/archive/v0.7.tar.gz

**Comment by akorosov** [comment]
@hamoun1981 , can you provide the names of images that give the error? So that I can reproduce that error and fix.
Maybe you can put these files on FTP?

**Comment by akorosov** [comment]
Can you also try to install a newer version:
pip install https://github.com/nansencenter/sea_ice_drift/archive/master.tar.gz

**Comment by hamoun1981** [comment]
Thanks, @akorosov 
here is five of them:

S1B_EW_GRDM_1SDH_20181129T084944_20181129T085044_013817_0199C0_AD90.SAFE
S1B_EW_GRDM_1SDH_20181130T093045_20181130T093145_013832_019A37_92D9.SAFE

S1B_EW_GRDM_1SDH_20181130T093045_20181130T093145_013832_019A37_92D9.SAFE
S1B_EW_GRDM_1SDH_20181204T085756_20181204T085856_013890_019C1C_84A0.SAFE

S1B_EW_GRDM_1SDH_20181211T084944_20181211T085044_013992_019F6A_EC56.SAFE
S1B_EW_GRDM_1SDH_20181212T093044_20181212T093144_014007_019FE5_4896.SAFE

S1B_EW_GRDM_1SDH_20181212T093044_20181212T093144_014007_019FE5_4896.SAFE
S1B_EW_GRDM_1SDH_20181216T085755_20181216T085855_014065_01A1D1_D6C2.SAFE

S1B_EW_GRDM_1SDH_20181223T084944_20181223T085044_014167_01A537_BDA1.SAFE
S1B_EW_GRDM_1SDH_20181224T093044_20181224T093144_014182_01A5AF_D832.SAFE

In the two cases, the time interval between the acquisition of images is around 4 days. I am aware of it. I just downloaded them for testing.

**Comment by hamoun1981** [comment]
Thanks again I will try the newer version.

**Comment by hamoun1981** [comment]
Thank you, I can run the algorithm with any pairs of SAR images (to be precise up to now) in my laptop with the following steps:
    • conda create -y -n new03 gdal=2.4.2 numpy pillow netcdf4 scipy
    • conda activate new03
    • pip install nansat
    • conda install nose opencv
    • pip install https://github.com/nansencenter/sea_ice_drift/archive/master.tar.gz
