### ISSUE TITLE
Need a help in preparation original Sentinel SAR image for the algorithm

### ISSUE THREAD

**Issue by hamoun1981** [nansencenter/sea_ice_drift#15]
Hello

I installed the library and run the example without a problem, but when I tried the original SAR images I faced with an error.

"ValueError: Cannot find band {'name': 'sigma0_HV'}! band_number is from 1 to 1"

so I checked the example and original files both and I found some differences in metadata:
Original file does not have this line NETCDF_VARNAME=sigma0_HV

One member of the group I am working in it recommended me to use "nansat_geotiffimage". I applied it but I still have the same problem

[Test.pdf](https://github.com/nansencenter/sea_ice_drift/files/2983798/Test.pdf)

thanks in advance for any help you can provide

Best regards,
Hamoun

**Comment by akorosov** [comment]
Hi @hamoun1981 !
How did you prepare these tif files? 
```
f1 = 'S1D_EW_GRDM_1SDH_20190311T080051.tif'
f2 = 'S1D_EW_GRDM_1SDH_20190311T093915.tif'
```
You actually don't need any extra preprocessing. 
The code can take original L1 EW GRDM Sentinel-1 data:
```
f1='S1A_EW_GRDM_1SDH_20190320T051001_20190320T051049_026417_02F4DD_3D0D.SAFE'
f2='S1A_EW_GRDM_1SDH_20190320T082602_20190320T082712_026419_02F4F4_568B.SAFE'
```

**Comment by hamoun1981** [comment]
Thanks a lot for your help
I applied nansat_geotiffimage on Geotiff file which one can find in "measurement" folder of downloaded Sentinel SAR images and formerly I utilized that "TIF" file instead of example input image which I faced with that problem.
