### ISSUE TITLE
Test data missing

### ISSUE THREAD

**Issue by mitkin** [nansencenter/sea_ice_drift#18]
`ftp.nersc.no/pub/nansat` folder is missing, so no test data is available. Not a big deal, but probably it's good idea to fix. Maybe through git-LFS to make it a part of repository?

**Comment by akorosov** [comment]
wget https://github.com/nansencenter/sea_ice_drift_test_files/raw/master/S1A_EW_GRDM_1SDH_20161005T142446.tif
wget https://github.com/nansencenter/sea_ice_drift_test_files/raw/master/S1B_EW_GRDM_1SDH_20161005T101835.tif
Also updated the Readme.
