### ISSUE TITLE
about the data of the input

### ISSUE THREAD

**Issue by LooperzZ** [nansencenter/sea_ice_drift#29]
There are a few questions I would like to ask about the data:
1. How is the sample data you gave processed, if it is also using Nansat, what APIs are used, and if it is other software, can you explain how to deal with it?
2. How can I read the .safe file directly?
thank you!

**Comment by akorosov** [comment]
No preprocessing is actually needed.

Please, have a look at the detailed.ipynb - I use SAFE files directly with Nansat.

Alternatively, if your files are openable with Nansat, but have some other relevant band than 'sigma0_HH' you can specify that in the parameter band_name to the get_n() function.
I.e. in case of GRDV it would be get_n(filename, bandName='sigma0_VV')


You can check if your installation of nansat works the following way:
In [1]: from nansat import Nansat

In [2]: n = Nansat('S1B_EW_GRDM_1SDH_20200125T114955_20200125T115055_019973_025C81_EC1A.SAFE')

In [3]: n.bands()
Out[3]: 
{1: {'dataType': '2',
  'name': 'DN_HH',
  'SourceBand': '1',
  'SourceFilename': 'S1B_EW_GRDM_1SDH_20200125T114955_20200125T115055_019973_025C81_EC1A.SAFE/measurement/s1b-ew-grd-hh-20200125t114955-20200125t115055-019973-025c81-001.tiff'},
 2: {'dataType': '2',
  'name': 'DN_HV',
  'SourceBand': '1',
  'SourceFilename': 'S1B_EW_GRDM_1SDH_20200125T114955_20200125T115055_019973_025C81_EC1A.SAFE/measurement/s1b-ew-grd-hv-20200125t114955-20200125t115055-019973-025c81-002.tiff'},
 3: {'dataType': '7',
  'name': 'sigmaNought_HH',
  'SourceBand': '1',
  'SourceFilename': '/vsimem/PZ0LC2WD7U.vrt'},
 4: {'dataType': '7',
  'name': 'noise_HH',
  'SourceBand': '1',
  'SourceFilename': '/vsimem/BWKH9VN73U.vrt'},
 5: {'dataType': '7',
  'name': 'sigmaNought_HV',
  'SourceBand': '1',
  'SourceFilename': '/vsimem/7EQEL20ESL.vrt'},
 6: {'dataType': '7',
  'name': 'noise_HV',
  'SourceBand': '1',
  'SourceFilename': '/vsimem/M3U719BDVQ.vrt'},
 7: {'colormap': 'jet',
  'dataType': '6',
  'long_name': 'Sensor Azimuth Angle',
  'minmax': '0 360',
  'name': 'look_direction',
  'short_name': 'sensor_azimuth',
  'SourceBand': '1',
  'SourceFilename': '/vsimem/U92I5GC9UV.vrt',
  'standard_name': 'sensor_azimuth_angle',
  'units': 'degrees',
  'wkv': 'sensor_azimuth_angle'},
 8: {'colormap': 'gray',
  'dataType': '6',
  'long_name': 'Normalized Radar Cross Section',
  'minmax': '0 0.1',
  'name': 'sigma0_HH',
  'PixelFunctionType': 'Sentinel1Calibration',
  'polarization': 'HH',
  'short_name': 'sigma0',
  'SourceBand': '1',
  'SourceFilename': '/vsimem/27XQF9KYL9.vrt',
  'standard_name': 'surface_backwards_scattering_coefficient_of_radar_wave',
  'suffix': 'HH',
  'units': 'm/m',
  'wkv': 'surface_backwards_scattering_coefficient_of_radar_wave'},
 9: {'colormap': 'gray',
  'dataType': '6',
  'long_name': 'Reflectivity per unit area in slant range',
  'minmax': '0 0.1',
  'name': 'beta0_HH',
  'PixelFunctionType': 'Sentinel1Calibration',
  'polarization': 'HH',
  'short_name': 'beta0',
  'SourceBand': '1',
  'SourceFilename': '/vsimem/27XQF9KYL9.vrt',
  'standard_name': 'surface_backwards_brightness_coefficient_of_radar_wave',
  'suffix': 'HH',
  'units': 'm/m',
  'wkv': 'surface_backwards_brightness_coefficient_of_radar_wave'},
 10: {'colormap': 'gray',
  'dataType': '6',
  'long_name': 'Normalized Radar Cross Section',
  'minmax': '0 0.1',
  'name': 'sigma0_HV',
  'PixelFunctionType': 'Sentinel1Calibration',
  'polarization': 'HV',
  'short_name': 'sigma0',
  'SourceBand': '2',
  'SourceFilename': '/vsimem/27XQF9KYL9.vrt',
  'standard_name': 'surface_backwards_scattering_coefficient_of_radar_wave',
  'suffix': 'HV',
  'units': 'm/m',
  'wkv': 'surface_backwards_scattering_coefficient_of_radar_wave'},
 11: {'colormap': 'gray',
  'dataType': '6',
  'long_name': 'Reflectivity per unit area in slant range',
  'minmax': '0 0.1',
  'name': 'beta0_HV',
  'PixelFunctionType': 'Sentinel1Calibration',
  'polarization': 'HV',
  'short_name': 'beta0',
  'SourceBand': '2',
  'SourceFilename': '/vsimem/27XQF9KYL9.vrt',
  'standard_name': 'surface_backwards_brightness_coefficient_of_radar_wave',
  'suffix': 'HV',
  'units': 'm/m',
  'wkv': 'surface_backwards_brightness_coefficient_of_radar_wave'},
 12: {'colormap': 'jet',
  'dataType': '7',
  'long_name': 'Incidence Angle',
  'minmax': '0 90',
  'name': 'incidence_angle',
  'short_name': 'incidence_angle',
  'SourceBand': '1',
  'SourceFilename': '/vsimem/CSYXEZACTJ.vrt',
  'standard_name': 'angle_of_incidence',
  'units': 'degrees',
  'wkv': 'angle_of_incidence'},
 13: {'dataType': '7',
  'name': 'elevation_angle',
  'SourceBand': '1',
  'SourceFilename': '/vsimem/11Y8SHFX8W.vrt',
  'wkv': 'angle_of_elevation'},
 14: {'colormap': 'gray',
  'dataType': '6',
  'long_name': 'Normalized Radar Cross Section',
  'minmax': '0 0.1',
  'name': 'sigma0_VV',
  'PixelFunctionType': 'Sentinel1Sigma0HHToSigma0VV',
  'polarization': 'VV',
  'short_name': 'sigma0',
  'SourceBand': '1',
  'SourceFilename': '/vsimem/27XQF9KYL9.vrt',
  'standard_name': 'surface_backwards_scattering_coefficient_of_radar_wave',
  'suffix': 'VV',
  'units': 'm/m',
  'wkv': 'surface_backwards_scattering_coefficient_of_radar_wave'}}

In [4]: b1 = n['sigma0_HH']

In [5]: print(b1.shape)
(9991, 10654)
