### ISSUE TITLE
Vectors direction 

### ISSUE THREAD

**Issue by SAMPHY86** [nansencenter/sea_ice_drift#8]
Hi,
Thank you for resolving the last issue. Now I tried running sea_ice_drift with the supplied test data but it shows all vectors for FT and PM in one (u) direction 
 
![sea_ice_drift_ft_img1](https://user-images.githubusercontent.com/29968261/28956019-7c530904-793e-11e7-98a6-2f8e6d4189ae.png)
![sea_ice_drift_pm_img2](https://user-images.githubusercontent.com/29968261/28956028-8570bd92-793e-11e7-8aa2-a9b447dc2fbe.png)

But when i multiplied the vft and vpm by a factor say 10, then it resembles the results provided on website

![sea_ice_drift_ft_img3](https://user-images.githubusercontent.com/29968261/28956104-05c9b444-793f-11e7-95e9-c7a1940487c7.png)
![sea_ice_drift_pm_img4](https://user-images.githubusercontent.com/29968261/28956111-0b4f5234-793f-11e7-989b-1acf761c13ff.png)

So is there any factor involves when try to plot the vectors? 
Many thanks, Usama

**Comment by akorosov** [comment]
Yes, there is.  Please see the simple.py file in folder examples.
https://github.com/nansencenter/sea_ice_drift/blob/add_mcc_functions/examples/simple.py
It shows hot to correctly do quiver plot when lon and lat have different
scales:

plt.quiver(lon1ft, lat1ft, uft, vft, color='r',
           angles='xy', scale_units='xy', scale=0.5)

**Comment by SAMPHY86** [comment]
Many thanks for your response! I got everything to work with the test data. Now I downloaded sentinel-1 data from ESA and I did a calibration using the SNAP software. Having it exported as a geotiff, I realized that the header information is different from the one provided in the sample data. So when I run the program I get the error below. Can I use SNAP to export the data in the right format, or did you use a different software?

Traceback (most recent call last):  
File "<stdin>", line 1, in <module>
  File "/home/ufa11/miniconda/lib/python2.7/site-packages/sea_ice_drift/seaicedrift.py", line 40, in __init__
    self.n1 = get_n(self.filename1, **kwargs)
  File "/home/ufa11/miniconda/lib/python2.7/site-packages/sea_ice_drift/lib.py", line 212, in get_n
    img = n[bandName]
  File "/home/ufa11/miniconda/lib/python2.7/site-packages/nansat/nansat.py", line 195, in __getitem__
    band = self.get_GDALRasterBand(bandID)
  File "/home/ufa11/miniconda/lib/python2.7/site-packages/nansat/nansat.py", line 1012, in get_GDALRasterBand
    bandNumber = self._get_band_number(bandID)
  File "/home/ufa11/miniconda/lib/python2.7/site-packages/nansat/nansat.py", line 1785, in _get_band_number
    % (str(bandID), self.vrt.dataset.RasterCount))
nansat.tools.OptionError: Cannot find band {'name': 'sigma0_HV'}! bandNumber is from 1 to 1

**Comment by akorosov** [comment]
It is better to have it as a separate issue. Nonetheless I can reply that I use Nansat for calibration of Sentinel-1 data. I'd also like to add that it is not strictly compulsory to use the SeaIceDrift class. In fact it was designed more for demonstration. You can use the function from ftlib and pmlib directly and be very flexible.
