### ISSUE TITLE
An Error.

### ISSUE THREAD

**Issue by schuman12** [nansencenter/sea_ice_drift#9]
Dear Anton Korosv,
When I run your example.
An error occurs in function sid.get_drift_PM().
It shows "AttributeError: Can't pickle local object 'pattern_matching.<locals>._init_pool'".
My system is Win 10 and I use anaconda.

**Comment by akorosov** [comment]
Dear @schuman12,
I cannot reproduce your error. I don't have access to Win10 machine. Can you try to install anaconda on a virtual machine with linux?
